/**
 * 1.
 * {
    "One Centavo": 100,
    "Five Centavo": 20,
    "Ten Centavo": 10,
    "Twenty-five Centavo": 4,
    "Fifty Centavo": 2
    }
 */
const tools = require("./Combinations");
/**
 * Test 1: Endpoint 1
 * Number of ways pennies, nickels, dimes, and quarters can sum exactly $1
 */
test("should have 242 unique combinations with each unique combination to make change for a dollar", () => {
  const combinations = tools.findCombinations();
  const count = combinations.length;
  const expectedCombinations = {
    count: count,
    combinations: combinations,
  };
  expect(expectedCombinations).toEqual({
    count: 242,
    combinations: [
      {
        pennies: 100,
        nickels: 0,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 95,
        nickels: 1,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 90,
        nickels: 2,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 90,
        nickels: 0,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 85,
        nickels: 3,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 85,
        nickels: 1,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 80,
        nickels: 4,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 80,
        nickels: 2,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 80,
        nickels: 0,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 75,
        nickels: 5,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 75,
        nickels: 3,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 75,
        nickels: 1,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 75,
        nickels: 0,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 70,
        nickels: 6,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 70,
        nickels: 4,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 70,
        nickels: 2,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 70,
        nickels: 1,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 70,
        nickels: 0,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 65,
        nickels: 7,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 65,
        nickels: 5,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 65,
        nickels: 3,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 65,
        nickels: 2,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 65,
        nickels: 1,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 65,
        nickels: 0,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 60,
        nickels: 8,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 60,
        nickels: 6,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 60,
        nickels: 4,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 60,
        nickels: 3,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 60,
        nickels: 2,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 60,
        nickels: 1,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 60,
        nickels: 0,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 55,
        nickels: 9,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 55,
        nickels: 7,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 55,
        nickels: 5,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 55,
        nickels: 4,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 55,
        nickels: 3,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 55,
        nickels: 2,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 55,
        nickels: 1,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 55,
        nickels: 0,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 50,
        nickels: 10,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 50,
        nickels: 8,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 50,
        nickels: 6,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 50,
        nickels: 5,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 50,
        nickels: 4,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 50,
        nickels: 3,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 50,
        nickels: 2,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 50,
        nickels: 1,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 50,
        nickels: 0,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 50,
        nickels: 0,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 45,
        nickels: 11,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 45,
        nickels: 9,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 45,
        nickels: 7,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 45,
        nickels: 6,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 45,
        nickels: 5,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 45,
        nickels: 4,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 45,
        nickels: 3,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 45,
        nickels: 2,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 45,
        nickels: 1,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 45,
        nickels: 1,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 45,
        nickels: 0,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 40,
        nickels: 12,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 10,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 8,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 7,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 40,
        nickels: 6,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 5,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 40,
        nickels: 4,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 3,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 40,
        nickels: 2,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 2,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 40,
        nickels: 1,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 40,
        nickels: 0,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 40,
        nickels: 0,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 35,
        nickels: 13,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 11,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 9,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 8,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 35,
        nickels: 7,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 6,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 35,
        nickels: 5,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 4,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 35,
        nickels: 3,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 3,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 35,
        nickels: 2,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 35,
        nickels: 1,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 35,
        nickels: 1,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 35,
        nickels: 0,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 30,
        nickels: 14,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 12,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 10,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 9,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 30,
        nickels: 8,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 7,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 30,
        nickels: 6,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 5,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 30,
        nickels: 4,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 4,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 30,
        nickels: 3,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 30,
        nickels: 2,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 2,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 30,
        nickels: 1,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 30,
        nickels: 0,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 30,
        nickels: 0,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 25,
        nickels: 15,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 13,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 11,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 10,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 25,
        nickels: 9,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 8,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 25,
        nickels: 7,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 6,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 25,
        nickels: 5,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 5,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 25,
        nickels: 4,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 25,
        nickels: 3,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 3,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 25,
        nickels: 2,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 25,
        nickels: 1,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 25,
        nickels: 1,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 25,
        nickels: 0,
        dimes: 5,
        quarters: 1,
      },
      {
        pennies: 25,
        nickels: 0,
        dimes: 0,
        quarters: 3,
      },
      {
        pennies: 20,
        nickels: 16,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 14,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 12,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 11,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 20,
        nickels: 10,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 9,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 20,
        nickels: 8,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 7,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 20,
        nickels: 6,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 6,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 20,
        nickels: 5,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 20,
        nickels: 4,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 4,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 20,
        nickels: 3,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 20,
        nickels: 2,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 2,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 20,
        nickels: 1,
        dimes: 5,
        quarters: 1,
      },
      {
        pennies: 20,
        nickels: 1,
        dimes: 0,
        quarters: 3,
      },
      {
        pennies: 20,
        nickels: 0,
        dimes: 8,
        quarters: 0,
      },
      {
        pennies: 20,
        nickels: 0,
        dimes: 3,
        quarters: 2,
      },
      {
        pennies: 15,
        nickels: 17,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 15,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 13,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 12,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 11,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 10,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 9,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 8,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 7,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 7,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 15,
        nickels: 6,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 5,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 5,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 15,
        nickels: 4,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 3,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 3,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 15,
        nickels: 2,
        dimes: 5,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 2,
        dimes: 0,
        quarters: 3,
      },
      {
        pennies: 15,
        nickels: 1,
        dimes: 8,
        quarters: 0,
      },
      {
        pennies: 15,
        nickels: 1,
        dimes: 3,
        quarters: 2,
      },
      {
        pennies: 15,
        nickels: 0,
        dimes: 6,
        quarters: 1,
      },
      {
        pennies: 15,
        nickels: 0,
        dimes: 1,
        quarters: 3,
      },
      {
        pennies: 10,
        nickels: 18,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 16,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 14,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 13,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 12,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 11,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 10,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 9,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 8,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 8,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 10,
        nickels: 7,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 6,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 6,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 10,
        nickels: 5,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 4,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 4,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 10,
        nickels: 3,
        dimes: 5,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 3,
        dimes: 0,
        quarters: 3,
      },
      {
        pennies: 10,
        nickels: 2,
        dimes: 8,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 2,
        dimes: 3,
        quarters: 2,
      },
      {
        pennies: 10,
        nickels: 1,
        dimes: 6,
        quarters: 1,
      },
      {
        pennies: 10,
        nickels: 1,
        dimes: 1,
        quarters: 3,
      },
      {
        pennies: 10,
        nickels: 0,
        dimes: 9,
        quarters: 0,
      },
      {
        pennies: 10,
        nickels: 0,
        dimes: 4,
        quarters: 2,
      },
      {
        pennies: 5,
        nickels: 19,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 17,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 15,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 14,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 13,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 12,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 11,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 10,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 9,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 9,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 5,
        nickels: 8,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 7,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 7,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 5,
        nickels: 6,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 5,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 5,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 5,
        nickels: 4,
        dimes: 5,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 4,
        dimes: 0,
        quarters: 3,
      },
      {
        pennies: 5,
        nickels: 3,
        dimes: 8,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 3,
        dimes: 3,
        quarters: 2,
      },
      {
        pennies: 5,
        nickels: 2,
        dimes: 6,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 2,
        dimes: 1,
        quarters: 3,
      },
      {
        pennies: 5,
        nickels: 1,
        dimes: 9,
        quarters: 0,
      },
      {
        pennies: 5,
        nickels: 1,
        dimes: 4,
        quarters: 2,
      },
      {
        pennies: 5,
        nickels: 0,
        dimes: 7,
        quarters: 1,
      },
      {
        pennies: 5,
        nickels: 0,
        dimes: 2,
        quarters: 3,
      },
      {
        pennies: 0,
        nickels: 20,
        dimes: 0,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 18,
        dimes: 1,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 16,
        dimes: 2,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 15,
        dimes: 0,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 14,
        dimes: 3,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 13,
        dimes: 1,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 12,
        dimes: 4,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 11,
        dimes: 2,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 10,
        dimes: 5,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 10,
        dimes: 0,
        quarters: 2,
      },
      {
        pennies: 0,
        nickels: 9,
        dimes: 3,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 8,
        dimes: 6,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 8,
        dimes: 1,
        quarters: 2,
      },
      {
        pennies: 0,
        nickels: 7,
        dimes: 4,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 6,
        dimes: 7,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 6,
        dimes: 2,
        quarters: 2,
      },
      {
        pennies: 0,
        nickels: 5,
        dimes: 5,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 5,
        dimes: 0,
        quarters: 3,
      },
      {
        pennies: 0,
        nickels: 4,
        dimes: 8,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 4,
        dimes: 3,
        quarters: 2,
      },
      {
        pennies: 0,
        nickels: 3,
        dimes: 6,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 3,
        dimes: 1,
        quarters: 3,
      },
      {
        pennies: 0,
        nickels: 2,
        dimes: 9,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 2,
        dimes: 4,
        quarters: 2,
      },
      {
        pennies: 0,
        nickels: 1,
        dimes: 7,
        quarters: 1,
      },
      {
        pennies: 0,
        nickels: 1,
        dimes: 2,
        quarters: 3,
      },
      {
        pennies: 0,
        nickels: 0,
        dimes: 10,
        quarters: 0,
      },
      {
        pennies: 0,
        nickels: 0,
        dimes: 5,
        quarters: 2,
      },
      {
        pennies: 0,
        nickels: 0,
        dimes: 0,
        quarters: 4,
      },
    ],
  });
});

/**
 * Test 2: Endpoint 2
 * Input parameters:
 * {
 *    Coin: 1.5,
 *    Arrowhead: 3,
 *    Button: 150,
 * }
 */

// figure out why when i move Button to the front of the object, that it is not correct with the same output
test("should have 6 unique combinations for 3 arbitrary currency names and denomination", () => {
  const arbitraryCombos = tools.findArbitraryCombinations({
    Coin: 1.5,
    Arrowhead: 3,
    Button: 150,
  });
  const count = arbitraryCombos.length;
  const expectedArbitraryCombos = {
    count: count,
    combinations: arbitraryCombos,
  };
  expect(expectedArbitraryCombos).toEqual(
    expect.objectContaining({
      count: 6,
      combinations: [
        {
          Button: 150,
          Arrowhead: 0,
          Coin: 0,
        },
        {
          Button: 100,
          Arrowhead: 1,
          Coin: 0,
        },
        {
          Button: 50,
          Arrowhead: 2,
          Coin: 0,
        },
        {
          Button: 50,
          Arrowhead: 0,
          Coin: 1,
        },
        {
          Button: 0,
          Arrowhead: 3,
          Coin: 0,
        },
        {
          Button: 0,
          Arrowhead: 1,
          Coin: 1,
        },
      ],
    })
  );
});

/**
 * Test 3: Endpoint 2 with a single parameter
 * Input parameters:
 * {
 *    Single: 10
 * }
 */
test("should have 1 unique combinations for 1 arbitrary currency name and denomination", () => {
  const arbitraryCombos = tools.findArbitraryCombinations({
    Single: 10,
  });
  const count = arbitraryCombos.length;
  const expectedArbitraryCombos = {
    count: count,
    combinations: arbitraryCombos,
  };
  expect(expectedArbitraryCombos).toEqual(
    expect.objectContaining({
      count: 1,
      combinations: [
        {
          Single: 10,
        },
      ],
    })
  );
});

/**
 * Test 4: Endpoint 2 with no parameters, error is thrown with message "The currency object is empty"
 * {
 * }
 */
test("should throw an error saying the object is empty", () => {
  expect(() => {
    tools.findArbitraryCombinations({});
  }).toThrow("The currency object is empty");
});

/**
     * Test 5: Endpoint 2 with random currency names and values that I made up
     * {
        "One Centavo": 100,
        "Five Centavo": 20,
        "Eight Centavo": 12.5,
        "Fifty Centavo": 2
       }
     */

test("should have 185 unique combinations, each should add up to 100", () => {
  const arbitraryCombos = tools.findArbitraryCombinations({
    "One Centavo": 100,
    "Five Centavo": 20,
    "Eight Centavo": 12.5,
    "Fifty Centavo": 2,
  });
  const count = arbitraryCombos.length;
  const expectedArbitraryCombos = {
    count: count,
    combinations: arbitraryCombos,
  };
  expect(expectedArbitraryCombos).toEqual(
    expect.objectContaining({
      count: 185,
      combinations: [
        {
          "One Centavo": 100,
          "Five Centavo": 0,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 95,
          "Five Centavo": 1,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 92,
          "Five Centavo": 0,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 90,
          "Five Centavo": 2,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 87,
          "Five Centavo": 1,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 85,
          "Five Centavo": 3,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 84,
          "Five Centavo": 0,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 82,
          "Five Centavo": 2,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 80,
          "Five Centavo": 4,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 79,
          "Five Centavo": 1,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 77,
          "Five Centavo": 3,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 76,
          "Five Centavo": 0,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 75,
          "Five Centavo": 5,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 74,
          "Five Centavo": 2,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 72,
          "Five Centavo": 4,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 71,
          "Five Centavo": 1,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 70,
          "Five Centavo": 6,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 69,
          "Five Centavo": 3,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 68,
          "Five Centavo": 0,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 67,
          "Five Centavo": 5,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 66,
          "Five Centavo": 2,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 65,
          "Five Centavo": 7,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 64,
          "Five Centavo": 4,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 63,
          "Five Centavo": 1,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 62,
          "Five Centavo": 6,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 61,
          "Five Centavo": 3,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 60,
          "Five Centavo": 8,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 60,
          "Five Centavo": 0,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 59,
          "Five Centavo": 5,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 58,
          "Five Centavo": 2,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 57,
          "Five Centavo": 7,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 56,
          "Five Centavo": 4,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 55,
          "Five Centavo": 9,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 55,
          "Five Centavo": 1,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 54,
          "Five Centavo": 6,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 53,
          "Five Centavo": 3,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 52,
          "Five Centavo": 8,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 52,
          "Five Centavo": 0,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 51,
          "Five Centavo": 5,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 50,
          "Five Centavo": 10,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 50,
          "Five Centavo": 2,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 50,
          "Five Centavo": 0,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 49,
          "Five Centavo": 7,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 48,
          "Five Centavo": 4,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 47,
          "Five Centavo": 9,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 47,
          "Five Centavo": 1,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 46,
          "Five Centavo": 6,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 45,
          "Five Centavo": 11,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 45,
          "Five Centavo": 3,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 45,
          "Five Centavo": 1,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 44,
          "Five Centavo": 8,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 44,
          "Five Centavo": 0,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 43,
          "Five Centavo": 5,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 42,
          "Five Centavo": 10,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 42,
          "Five Centavo": 2,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 42,
          "Five Centavo": 0,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 41,
          "Five Centavo": 7,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 40,
          "Five Centavo": 12,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 40,
          "Five Centavo": 4,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 40,
          "Five Centavo": 2,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 39,
          "Five Centavo": 9,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 39,
          "Five Centavo": 1,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 38,
          "Five Centavo": 6,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 37,
          "Five Centavo": 11,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 37,
          "Five Centavo": 3,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 37,
          "Five Centavo": 1,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 36,
          "Five Centavo": 8,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 36,
          "Five Centavo": 0,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 35,
          "Five Centavo": 13,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 35,
          "Five Centavo": 5,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 35,
          "Five Centavo": 3,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 34,
          "Five Centavo": 10,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 34,
          "Five Centavo": 2,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 34,
          "Five Centavo": 0,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 33,
          "Five Centavo": 7,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 32,
          "Five Centavo": 12,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 32,
          "Five Centavo": 4,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 32,
          "Five Centavo": 2,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 31,
          "Five Centavo": 9,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 31,
          "Five Centavo": 1,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 30,
          "Five Centavo": 14,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 30,
          "Five Centavo": 6,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 30,
          "Five Centavo": 4,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 29,
          "Five Centavo": 11,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 29,
          "Five Centavo": 3,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 29,
          "Five Centavo": 1,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 28,
          "Five Centavo": 8,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 28,
          "Five Centavo": 0,
          "Eight Centavo": 9,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 27,
          "Five Centavo": 13,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 27,
          "Five Centavo": 5,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 27,
          "Five Centavo": 3,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 26,
          "Five Centavo": 10,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 26,
          "Five Centavo": 2,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 26,
          "Five Centavo": 0,
          "Eight Centavo": 3,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 25,
          "Five Centavo": 15,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 25,
          "Five Centavo": 7,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 25,
          "Five Centavo": 5,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 24,
          "Five Centavo": 12,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 24,
          "Five Centavo": 4,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 24,
          "Five Centavo": 2,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 23,
          "Five Centavo": 9,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 23,
          "Five Centavo": 1,
          "Eight Centavo": 9,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 22,
          "Five Centavo": 14,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 22,
          "Five Centavo": 6,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 22,
          "Five Centavo": 4,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 21,
          "Five Centavo": 11,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 21,
          "Five Centavo": 3,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 21,
          "Five Centavo": 1,
          "Eight Centavo": 3,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 20,
          "Five Centavo": 16,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 20,
          "Five Centavo": 8,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 20,
          "Five Centavo": 6,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 20,
          "Five Centavo": 0,
          "Eight Centavo": 10,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 19,
          "Five Centavo": 13,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 19,
          "Five Centavo": 5,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 19,
          "Five Centavo": 3,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 18,
          "Five Centavo": 10,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 18,
          "Five Centavo": 2,
          "Eight Centavo": 9,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 18,
          "Five Centavo": 0,
          "Eight Centavo": 4,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 17,
          "Five Centavo": 15,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 17,
          "Five Centavo": 7,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 17,
          "Five Centavo": 5,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 16,
          "Five Centavo": 12,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 16,
          "Five Centavo": 4,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 16,
          "Five Centavo": 2,
          "Eight Centavo": 3,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 15,
          "Five Centavo": 17,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 15,
          "Five Centavo": 9,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 15,
          "Five Centavo": 7,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 15,
          "Five Centavo": 1,
          "Eight Centavo": 10,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 14,
          "Five Centavo": 14,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 14,
          "Five Centavo": 6,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 14,
          "Five Centavo": 4,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 13,
          "Five Centavo": 11,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 13,
          "Five Centavo": 3,
          "Eight Centavo": 9,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 13,
          "Five Centavo": 1,
          "Eight Centavo": 4,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 12,
          "Five Centavo": 16,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 12,
          "Five Centavo": 8,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 12,
          "Five Centavo": 6,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 12,
          "Five Centavo": 0,
          "Eight Centavo": 11,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 11,
          "Five Centavo": 13,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 11,
          "Five Centavo": 5,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 11,
          "Five Centavo": 3,
          "Eight Centavo": 3,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 10,
          "Five Centavo": 18,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 10,
          "Five Centavo": 10,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 10,
          "Five Centavo": 8,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 10,
          "Five Centavo": 2,
          "Eight Centavo": 10,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 10,
          "Five Centavo": 0,
          "Eight Centavo": 5,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 9,
          "Five Centavo": 15,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 9,
          "Five Centavo": 7,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 9,
          "Five Centavo": 5,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 8,
          "Five Centavo": 12,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 8,
          "Five Centavo": 4,
          "Eight Centavo": 9,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 8,
          "Five Centavo": 2,
          "Eight Centavo": 4,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 7,
          "Five Centavo": 17,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 7,
          "Five Centavo": 9,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 7,
          "Five Centavo": 7,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 7,
          "Five Centavo": 1,
          "Eight Centavo": 11,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 6,
          "Five Centavo": 14,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 6,
          "Five Centavo": 6,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 6,
          "Five Centavo": 4,
          "Eight Centavo": 3,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 5,
          "Five Centavo": 19,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 5,
          "Five Centavo": 11,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 5,
          "Five Centavo": 9,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 5,
          "Five Centavo": 3,
          "Eight Centavo": 10,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 5,
          "Five Centavo": 1,
          "Eight Centavo": 5,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 4,
          "Five Centavo": 16,
          "Eight Centavo": 2,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 4,
          "Five Centavo": 8,
          "Eight Centavo": 7,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 4,
          "Five Centavo": 6,
          "Eight Centavo": 2,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 4,
          "Five Centavo": 0,
          "Eight Centavo": 12,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 3,
          "Five Centavo": 13,
          "Eight Centavo": 4,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 3,
          "Five Centavo": 5,
          "Eight Centavo": 9,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 3,
          "Five Centavo": 3,
          "Eight Centavo": 4,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 2,
          "Five Centavo": 18,
          "Eight Centavo": 1,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 2,
          "Five Centavo": 10,
          "Eight Centavo": 6,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 2,
          "Five Centavo": 8,
          "Eight Centavo": 1,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 2,
          "Five Centavo": 2,
          "Eight Centavo": 11,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 2,
          "Five Centavo": 0,
          "Eight Centavo": 6,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 1,
          "Five Centavo": 15,
          "Eight Centavo": 3,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 1,
          "Five Centavo": 7,
          "Eight Centavo": 8,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 1,
          "Five Centavo": 5,
          "Eight Centavo": 3,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 0,
          "Five Centavo": 20,
          "Eight Centavo": 0,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 0,
          "Five Centavo": 12,
          "Eight Centavo": 5,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 0,
          "Five Centavo": 10,
          "Eight Centavo": 0,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 0,
          "Five Centavo": 4,
          "Eight Centavo": 10,
          "Fifty Centavo": 0,
        },
        {
          "One Centavo": 0,
          "Five Centavo": 2,
          "Eight Centavo": 5,
          "Fifty Centavo": 1,
        },
        {
          "One Centavo": 0,
          "Five Centavo": 0,
          "Eight Centavo": 0,
          "Fifty Centavo": 2,
        },
      ],
    })
  );
});

/**
 * Test 6: Endpoint 2 with duplicate coin value, error is thrown with message saying
 * Input parameters contain a duplicate coin denomination/value
 */
test("should throw an error saying input parameters have a duplicate value", () => {
  expect(() => {
    tools.findArbitraryCombinations({
      pennies: 100,
      button: 100,
      doge: 50,
    });
  }).toThrow("Input parameters contain a duplicate coin denomination/value");
});
